packages:
  - apps/*
  - "!apps/data-pipeline"
  - apps/data-pipeline/*
  - packages/*
  - "!packages/public"
  - packages/public/*

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@biomejs/biome"
  - esbuild
  - lefthook
  - sharp
  - workerd
