# Prevents installation of packages less than 1 day old
minimumReleaseAge: 1440

packages:
  - "apps/*"
  - "!apps/data-pipeline"
  - "apps/data-pipeline/*"
  - "packages/*"
  - "!packages/public"
  - "packages/public/*"
