packages:
  - apps/*
  - "!apps/data-pipeline"
  - apps/data-pipeline/*
  - packages/*
  - "!packages/public"
  - packages/public/*

catalog:
  "@types/json-diff": 1.0.3
  "@types/readline-sync": 1.4.8
  cheerio: 1.2.0
  drizzle-kit: 0.31.10
  drizzle-ork: 0.45.2
  domhandler: 6.0.1
  json-diff: 1.0.6
  readline-sync: 1.4.10
  sort-keys: 6.0.1
  typescript: ^6.0.3
  winston: 3.19.0
  wrangler: 4.106.0
  zod: 4.4.2

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@biomejs/biome"
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
  - workerd

overrides:
  "@auth/core": 0.41.2
