#:schema node_modules/wrangler/config-schema.json
name = "anteater-api_websoc-scraper"
compatibility_date = "2024-09-28"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
main = "src/index.ts"
minify = true

[triggers]
crons = ["*/5 * * * *"]

[observability]
enabled = true

[[hyperdrive]]
binding = "DB"
id = "c498e76d4f68446ea55d0d92865257b5"
