#:schema node_modules/wrangler/config-schema.json
name = "anteater-api_key-manager"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "API_KEYS", id = "4c8dd3090bea4d469cd3c66b3002a5a2" },
]

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

workers_dev = false
route = { pattern = "dashboard.anteaterapi.com", zone_name = "anteaterapi.com", custom_domain = true }

[observability]
enabled = true
