# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Delete inactive API staging instance

on:
  pull_request:
    types:
      - closed

permissions:
  id-token: write
  contents: read
  pull-requests: write
  deployments: write
  repository-projects: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
jobs:
  delete_staging:
    name: Delete inactive API staging instance

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-and-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Delete inactive API staging instance
        working-directory: ./apps/api
        run: pnpm wrangler delete --name=anteater-api-staging-${{ github.event.pull_request.number }}

      - name: Set API staging environment to inactive
        uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: staging-${{ github.event.pull_request.number }}
          onlyDeactivateDeployments: true
